# coding: utf-8

# flake8: noqa
"""
    My mem API

    Swagger for mem API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.mem_threshold_model import MemThresholdModel
