# coding: utf-8

"""
    My mem API

    Swagger for mem API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.mem_threshold_model import MemThresholdModel  # noqa: E501
from openapi_client.rest import ApiException

class TestMemThresholdModel(unittest.TestCase):
    """MemThresholdModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MemThresholdModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.mem_threshold_model.MemThresholdModel()  # noqa: E501
        if include_optional :
            return MemThresholdModel(
                threshold = 56
            )
        else :
            return MemThresholdModel(
                threshold = 56,
        )

    def testMemThresholdModel(self):
        """Test MemThresholdModel"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
