# coding: utf-8

"""
    My mem API

    Swagger for mem API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.api_api import ApiApi  # noqa: E501
from openapi_client.rest import ApiException


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.api_api.ApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_home_api(self):
        """Test case for get_home_api

        """
        pass

    def test_get_mem_usage_api(self):
        """Test case for get_mem_usage_api

        """
        pass

    def test_post_mem_usage_api(self):
        """Test case for post_mem_usage_api

        """
        pass


if __name__ == '__main__':
    unittest.main()
